title:
#remote_theme: pages-themes/slate@v0.2.0
#plugins:
#- jekyll-remote-theme

author:
  name: Michael Wieck-Sosa
  email: mwiecksosa@cmu.edu
  
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
